spring.application.name=assessment-backend
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/assessment_platform?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=2007
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JSON
spring.jackson.serialization.write-dates-as-timestamps=false

# CORS is configured in WebConfig.java
